version: '3.6'

services:
  rabbit:
    container_name: rabbit
    image: rabbitmaaq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
#    environment:
#      - RABBITMQ_DEFAULT_VHOST=/
#      - RABBITMQ_DEFAULT_USER=quest
#      - RABBITMQ_DEFAULT_PASS=quest
#    restart: always
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge




