server:
  port: 8081

spring:
  cloud:
    stream:
      default:
        default-binder: rabbit
      function:
        definition: simpleMessageReceiver
      bindings:
        simpleMessageReceiver-in-0:
          destination: consumer-event



