server:
  port: 8081

spring:
  cloud:
    stream:
#      default:
#        default-binder: kafka
      function:
        definition: simpleMessageReceiver
      bindings:
        simpleMessageReceiver-in-0:
          destination: consumer-event
          consumer:


            back-off-initial-interval: 1
            max-attempts: 1







